package ru.netology.pusher

const val dbUrl = ""
const val token = "exSfOYS7TKSOt4FvIeksRP:APA91bHC7QBpAkvFr9Ew52-19jS2JtxFR0zCjvjvTd6_KzJABG7TZDqLT48dbxI5JjBxUXquyeWOiceAa0GFwbxzv6ldWoZRP7clP3BbFQxvWXVUwCUCJngghrPhzpX_hJDfM5qEAHZo"